"""Shared numeric constants for the Appwrite client package."""

DEFAULT_CACHE_TTL_HOURS = 24
DEFAULT_PAGE_LIMIT = 100
DEFAULT_TIMEOUT_SECONDS = 30
DEFAULT_CONNECT_TIMEOUT_SECONDS = 10
MAX_ATTRIBUTE_CREATION_RETRIES = 3
INITIAL_RETRY_DELAY = 1.0
